const demoProducts = [
  {id:"flares",title:"She Did It Anyway Flares",category:"Bottoms",price:"$298",description:"Made-to-order super flares with a low-rise foldover waist and customer-selected inseam.",tags:["Made to order","Selected inseam","Cut & sewn in USA"],shopUrl:"https://phural.shop"},
  {id:"leggings",title:"Made For More Leggings",category:"Activewear",price:"$128+",description:"High-compression nylon-spandex leggings with smooth construction and pocket/no-pocket options.",tags:["Compression","Cut & sewn in USA"],shopUrl:"https://phural.shop"},
  {id:"brakini",title:"Cardio to Cabana Bra-kini",category:"Swim",price:"$128+",description:"Convertible sports bra and bikini top with gold hardware and an X-back strap layout.",tags:["Convertible","Gold hardware","Cut & sewn in USA"],shopUrl:"https://phural.shop"},
  {id:"bottoms",title:"Thanks For The Space Bikini Bottoms",category:"Swim",price:"$98+",description:"Adjustable bikini bottoms designed for personalized fit.",tags:["Adjustable","Cut & sewn in USA"],shopUrl:"https://phural.shop"},
  {id:"tank",title:"Let Them Talk Tank",category:"Tops",price:"$98+",description:"Premium nylon-spandex tank designed to pair with Phural’s compression bottoms.",tags:["Premium compression","Cut & sewn in USA"],shopUrl:"https://phural.shop"},
  {id:"dress",title:"She Arrived Sequin Dress",category:"Dresses",price:"$298+",description:"Statement sequin mini dress from Phural’s occasion collection.",tags:["Statement","Made to order"],shopUrl:"https://phural.shop"},
  {id:"blazer",title:"Phural Structured Blazer",category:"Outerwear",price:"Coming soon",description:"Made-to-order tailored blazer with a structured stand collar and strong shoulder line.",tags:["Made to order","Tailoring","Cut & sewn in USA"],shopUrl:"https://phural.shop"}
];
let products=demoProducts, activeCategory="All";
const grid=document.getElementById("productGrid"), search=document.getElementById("searchInput"), filters=document.getElementById("categoryFilters");
function renderFilters(){const cats=["All",...new Set(products.map(p=>p.category))];filters.innerHTML=cats.map(c=>`<button class="chip ${c===activeCategory?'active':''}" data-cat="${c}">${c}</button>`).join("");filters.querySelectorAll(".chip").forEach(btn=>btn.addEventListener("click",()=>{activeCategory=btn.dataset.cat;renderFilters();renderProducts();}));}
function renderProducts(){const q=search.value.trim().toLowerCase();const filtered=products.filter(p=>(activeCategory==="All"||p.category===activeCategory)&&(!q||[p.title,p.category,p.description,...p.tags].join(" ").toLowerCase().includes(q)));grid.innerHTML=filtered.map(p=>`<article class="product-card" data-id="${p.id}" role="link" tabindex="0"><div class="product-image">${p.imageUrl?`<img src="${p.imageUrl}" alt="${p.imageAlt||p.title}" loading="lazy"><span class="image-fallback" style="display:none">${p.category}</span>`:`<span>${p.category}</span>`}</div><div class="product-body"><h4>${p.title}</h4><div class="product-meta">${p.tags.slice(0,2).join(" • ")}</div><div class="product-price">${p.price}</div></div></article>`).join("");
const openCard=card=>{const p=products.find(x=>x.id===card.dataset.id);if(p?.shopUrl) window.open(p.shopUrl,"_blank","noopener");};grid.querySelectorAll(".product-card").forEach(card=>{card.addEventListener("click",()=>openCard(card));card.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();openCard(card);}});});}
async function loadShopifyProducts(){const cfg=window.SAMIH_CONFIG||{};if(!cfg.shopDomain||!cfg.publicStorefrontToken)return;const endpoint=`https://${cfg.shopDomain}/api/${cfg.apiVersion||'2026-07'}/graphql.json`;const query=`query Products { products(first: 30) { nodes { id title handle productType description onlineStoreUrl images(first: 1) { nodes { url altText } } priceRange { minVariantPrice { amount currencyCode } } } } }`;try{const res=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json","X-Shopify-Storefront-Access-Token":cfg.publicStorefrontToken},body:JSON.stringify({query})});const payload=await res.json();if(!res.ok||payload.errors)throw new Error("Shopify request failed");const nodes=payload?.data?.products?.nodes||[];if(nodes.length)products=nodes.map(p=>({id:p.id,title:p.title,category:p.productType||"Phural",price:new Intl.NumberFormat("en-US",{style:"currency",currency:p.priceRange.minVariantPrice.currencyCode}).format(Number(p.priceRange.minVariantPrice.amount)),description:p.description||"Phural product",tags:["Phural","Shopify catalog"],imageUrl:p.images?.nodes?.[0]?.url||"",imageAlt:p.images?.nodes?.[0]?.altText||p.title,shopUrl:p.onlineStoreUrl||`https://phural.shop/products/${p.handle}`}));}catch(err){console.warn("Using demo catalog:",err.message);}}
search.addEventListener("input",renderProducts);const brandDialog=document.getElementById("brandDialog");document.getElementById("brandDetailsBtn").addEventListener("click",()=>brandDialog.showModal());document.getElementById("closeBrand").addEventListener("click",()=>brandDialog.close());
(async function init(){await loadShopifyProducts();renderFilters();renderProducts();})();
